-- Script de Correção Definitiva de ID (Detectar e Corrigir)

DO $$
DECLARE
    col_type text;
BEGIN
    -- Descobrir o tipo da coluna ID
    SELECT data_type INTO col_type FROM information_schema.columns 
    WHERE table_name = 'products' AND column_name = 'id';
    
    RAISE NOTICE 'Tipo da coluna ID detectado: %', col_type;

    -- CENÁRIO 1: Se for UUID
    IF col_type = 'uuid' THEN
        -- Remover identidade se existir
        BEGIN
            ALTER TABLE public.products ALTER COLUMN id DROP IDENTITY IF EXISTS;
        EXCEPTION WHEN OTHERS THEN NULL; END;
        
        -- Definir default para gerar UUID
        CREATE EXTENSION IF NOT EXISTS "pgcrypto"; -- Garante que gen_random_uuid funcione
        ALTER TABLE public.products ALTER COLUMN id SET DEFAULT gen_random_uuid();
        
        RAISE NOTICE 'Sucesso: ID configurado como UUID auto-gerado.';
        
    -- CENÁRIO 2: Se for Numérico (bigint, integer)
    ELSIF col_type IN ('bigint', 'integer', 'smallint', 'numeric') THEN
        -- Remover identidade antiga e default
        BEGIN
            ALTER TABLE public.products ALTER COLUMN id DROP IDENTITY IF EXISTS;
            ALTER TABLE public.products ALTER COLUMN id DROP DEFAULT;
        EXCEPTION WHEN OTHERS THEN NULL; END;
        
        -- Criar nova identidade
        ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
        
        -- Sincronizar a sequência com o maior ID existente
        EXECUTE 'SELECT setval(pg_get_serial_sequence(''public.products'', ''id''), COALESCE(MAX(id), 0) + 1, false) FROM public.products';
        
        RAISE NOTICE 'Sucesso: ID configurado como Auto-Incremento (Identity).';
    
    ELSE
        RAISE NOTICE 'Tipo de coluna inesperado: %. Nenhuma alteração feita.', col_type;
    END IF;
END $$;

NOTIFY pgrst, 'reload schema';
