-- Script de Correção de ID (Forçar Identidade)
-- Este script remove qualquer configuração de identidade existente e recria.

DO $$
BEGIN
    -- Tentar remover a identidade existente (caso esteja quebrada)
    BEGIN
        ALTER TABLE public.products ALTER COLUMN id DROP IDENTITY IF EXISTS;
    EXCEPTION
        WHEN OTHERS THEN
            RAISE NOTICE 'Erro ao remover identidade (pode não existir): %', SQLERRM;
    END;

    -- Tentar remover valor default (caso exista)
    ALTER TABLE public.products ALTER COLUMN id DROP DEFAULT;

    -- Adicionar identidade (GENERATED BY DEFAULT)
    -- Isso permite que o banco gere o ID se ele não for passado.
    ALTER TABLE public.products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    
    RAISE NOTICE 'Coluna ID configurada como GENERATED BY DEFAULT AS IDENTITY.';
EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Erro ao configurar identidade: %', SQLERRM;
END $$;

-- Sincronizar a sequência
DO $$
DECLARE
    max_id bigint;
BEGIN
    SELECT COALESCE(MAX(id), 0) INTO max_id FROM public.products;
    EXECUTE 'ALTER TABLE public.products ALTER COLUMN id RESTART WITH ' || (max_id + 1);
END $$;

NOTIFY pgrst, 'reload schema';
